### ISSUE TITLE
Repeat Result

### ISSUE THREAD

**Issue by PigUnderRoof** [futianfan/DST#1]
Hi @futianfan, interesting work! I am trying to get the result in Figure 3, is it possible to share the script? Thx.

**Comment by PigUnderRoof** [comment]
How do u pick the initial 1.5K training data, and how do u pick the initial smiles list?

**Comment by futianfan** [comment]
via random shuffle, from zinc. see https://github.com/wenhao-gao/mol_opt for standard benchmark for molecule optimization. all the detailed setup are available. thanks

**Comment by PigUnderRoof** [comment]
This is exactly what I want. Thank you very much @futianfan
