### ISSUE TITLE
pretain model

### ISSUE THREAD

**Issue by mapengsen** [futianfan/DST#3]
can you release your pretain model(pkl)?

thanks

**Comment by futianfan** [comment]
hi Pengsen, 

sorry i didn't save the pretrained model. 

However, the latest DST version is in the benchmark, where we train the GNN model online to save oracle calls. you can run DST based on one-line code: "python run.py DST --task production --n_runs 5 --oracles qed". 

free feel to raise an issue if it doesn't work. thanks for your interest!

**Comment by mapengsen** [comment]
okay，can i ask the time for train the model ? 
and the GPU for the train of your configuration ?

**Comment by futianfan** [comment]
train GNN is fast, within several minutes. but the whole pipeline may takes 2 hours. thanks, CPU is sufficient. thanks
